fixes 0.x compatibility for setAltInterface()
If pyusb-0.x code is used and
DeviceHandle.setConfiguration(self.dev.configurations[0])
is called, the following trace is printed:

  self.handle.setAltInterface(self.intf)
File "/home/andrey/tmp/pyusb/usb/legacy.py", line 267, in setAltInterface
  self.dev.set_interface_altsetting(self.__claimed_interface, alternate)
File "/home/andrey/tmp/pyusb/usb/core.py", line 872, in set_interface_altsetting
  self._ctx.managed_set_interface(self, interface, alternate_setting)
File "/home/andrey/tmp/pyusb/usb/core.py", line 177, in managed_set_interface
  self.managed_claim_interface(device, i)
File "/home/andrey/tmp/pyusb/usb/core.py", line 147, in managed_claim_interface
  self.backend.claim_interface(self.handle, i)
File "/home/andrey/tmp/pyusb/usb/backend/libusb1.py", line 803, in claim_interface
  _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: wrong type

If legacy function DeviceHandle.setAltInterface(self.intf) is
called, function _ResourceManager.managed_set_configuration 'config'
parameter's type will be <class 'usb.legacy.Interface' instead of
'int'.