fixes 0.x compatibility for setConfiguration()
If pyusb-0.x code is used and
DeviceHandle.setConfiguration(self.dev.configurations[0])
is called, the following trace is printed:

File "./mp709.py", line 109, in open
  self.handle.setConfiguration(self.dev.configurations[0])
File "/home/andrey/tmp/pyusb/usb/legacy.py", line 259, in setConfiguration
  self.dev.set_configuration(configuration)
File "/home/andrey/tmp/pyusb/usb/core.py", line 839, in set_configuration
  self._ctx.managed_set_configuration(self, configuration)
File "/home/andrey/tmp/pyusb/usb/core.py", line 129, in managed_set_configuration
  self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
AttributeError: 'NoneType' object has no attribute 'bConfigurationValue'

The problem is here, that in function
_ResourceManager.managed_set_configuration(self, device, config)
'config' parameter has type 'usb.legacy.Configuration' from legacy code.
But the function (managed_set_configuration) expects  types 'usb.core.Configuration' or 'int'.
With this patch  managed_set_configuration gets 'int' configuration
number from legacy code and util.find_descriptor(device, bConfigurationValue=config)
finds and returns corresponding 'usb.core.Configuration' for further handling.